// src/components/more-jobs.svelte
<script lang="ts">
  import { BASE_URL } from '@/shared/consts'

  interface Props {
    loading: boolean
    action: () => Promise<void>
  }

  let { action, loading }: Props = $props()
</script>

<footer class="w-full grid gap-y-2 justify-items-center">
  {#if loading}
    <img alt="Doge" src="{BASE_URL}/doge.png" class="w-16" />
    <span class="font-poppins">Loading more jobs...</span>
  {:else}
    <button class="btn outline w-max" onclick={action}>Load more jobs</button>
  {/if}
</footer>

// src/components/MoreJobs.jsx
import useJobs from '@/hooks/useJobs'
import { BASE_URL } from '@/consts'

export default function MoreJobs({ jobSetState }) {
  const { updateJobList, loading } = useJobs(jobSetState)

  return (
    <div className="grid justify-items-center pt-6">
      {loading ? <Loading /> : <GetMoreJobs action={updateJobList} />}
    </div>
  )
}

function Loading() {
  return (
    <>
      <img alt="Doge" src={BASE_URL + '/doge.png'} className="w-16" />
      <span className="font-poppins">Loading more jobs...</span>
    </>
  )
}

function GetMoreJobs({ action }) {
  return (
    <button className="btn outline" onClick={action}>
      Load more jobs
    </button>
  )
}
